import './interpret.test';
import { captureEndState } from '../src/core/engine/snapshot';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseNpy, parseAnchors, loadDataset, TRAITS, type Dataset } from '../src/core/data/loadDataset';
import { MemeticEngine } from '../src/core/engine/MemeticEngine';
import { EvolutionEngine } from '../src/core/engine/EvolutionEngine';
import { DEFAULT_CONFIG } from '../src/core/engine/config';
import { Rng } from '../src/core/math/random';
import { dot, norm, clamp } from '../src/core/math/vector';
import { PcaProjector } from '../src/core/math/pca';
import { useSimStore } from '../src/store/useSimStore';

const bytes = readFileSync('public/tweet_embeddings.npy');
const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
const vectors = parseNpy(buffer);
assert.equal(vectors.length, 200);
for (const v of vectors) { assert.equal(v.length, 256); assert.ok(Math.abs(norm(v) - 1) < 1e-12); }
assert.throws(() => parseNpy(buffer.slice(0, -1)), /payload/);
assert.throws(() => parseNpy(new ArrayBuffer(4)), /signature/);
assert.throws(() => parseAnchors({}), /256/);
assert.throws(() => parseAnchors(Object.fromEntries(TRAITS.map(t => [t, Array(256).fill(0)]))), /zero/);
// Independent NPY fixtures exercise endian, layout, width, and header versions.
for (const version of [1, 2, 3]) for (const width of [2, 4, 8]) for (const little of [true, false]) for (const fortran of [true, false]) {
  const header = new TextEncoder().encode(`{'descr': '${little ? '<' : '>'}f${width}', 'fortran_order': ${fortran ? 'True' : 'False'}, 'shape': (2, 256), }\n`);
  const start = version === 1 ? 10 : 12;
  const fixture = new ArrayBuffer(start + header.length + 2 * 256 * width);
  new Uint8Array(fixture).set([147, 78, 85, 77, 80, 89, version, 0]);
  const view = new DataView(fixture);
  if (version === 1) view.setUint16(8, header.length, true); else view.setUint32(8, header.length, true);
  new Uint8Array(fixture, start, header.length).set(header);
  for (let row = 0; row < 2; row++) for (let col = 0; col < 256; col++) {
    const value = col === row ? (row === 0 ? 1 : -1) : 0;
    const offset = start + header.length + (fortran ? col * 2 + row : row * 256 + col) * width;
    if (width === 2) view.setUint16(offset, value === 1 ? 0x3c00 : value === -1 ? 0xbc00 : 0, little);
    else if (width === 4) view.setFloat32(offset, value, little); else view.setFloat64(offset, value, little);
  }
  const parsed = parseNpy(fixture, 2);
  assert.equal(parsed[0][0], 1); assert.equal(parsed[1][1], -1);
  assert.equal(parsed[0][1], 0); assert.equal(parsed[1][0], 0);
}
// Test fixture anchors only: these are not semantic anchors and never ship as data.
const anchorsJson = Object.fromEntries(TRAITS.map((t, i) => [t, Array.from({ length: 256 }, (_, d) => +(i === d))]));
const data: Dataset = { tweets: JSON.parse(readFileSync('public/memetic_tweets.json', 'utf8')), vectors, anchors: parseAnchors(anchorsJson) };
const engine = new MemeticEngine({ ...DEFAULT_CONFIG, agentCount: 100, mutationProbability: 0.5 });
engine.initialize(data);
assert.equal(engine.roots.length, 200);
assert.equal(engine.roots[0].text, data.tweets[0].text);
assert.deepEqual(engine.roots[0].vector, vectors[0]);
const root = engine.roots[0], sender = engine.agents[0];
const evolution = new EvolutionEngine(data.anchors);
const child = evolution.mutate(root, root, sender, engine.config, 1, new Rng(99));
assert.equal(child.generation, 1);
assert.equal(child.parentId, root.id);
assert.equal(child.rootId, root.id);
assert.equal(child.selection!.fitness.length, 5);
assert.equal(child.selection!.fitness[child.selection!.winner], Math.max(...child.selection!.fitness));
assert.ok(Math.abs(norm(child.vector) - 1) < 1e-12);
assert.equal(child.rationality, clamp(0.5 - 0.5 * dot(child.vector, data.anchors.rigor) + 0.5 * dot(child.vector, data.anchors.outrage), 0, 1));
assert.equal(child.virality, clamp(0.3 + 0.4 * dot(child.vector, data.anchors.outrage) + 0.3 * dot(child.vector, data.anchors.simplicity), 0, 1));
assert.ok(Math.abs(child.driftDistance - (1 - dot(child.vector, root.vector))) < 1e-12);
const agentOnly = evolution.mutate(root, root, sender, { ...engine.config, platformSelection: 0 }, 1, new Rng(99));
assert.equal(agentOnly.selection!.weights[0], sender.epistemicRigor);
const platformOnly = evolution.mutate(root, root, sender, { ...engine.config, platformSelection: 1 }, 1, new Rng(99));
assert.deepEqual(platformOnly.selection!.weights, [0.1, 1, 0.4, 0.8]);
const fixedRootPosition = engine.cosmosProjector.project(root.vector);
const originalRigor = sender.epistemicRigor;
const run = () => { for (let i = 0; i < 240; i++) engine.step(); };
const start = performance.now(); run();
assert.deepEqual(engine.cosmosProjector.project(root.vector), fixedRootPosition);
assert.equal(engine.roots.length, 200);
for (const m of engine.memes.values()) { assert.ok(engine.memes.has(m.rootId)); if (m.parentId) assert.ok(engine.memes.has(m.parentId)); }
assert.ok(engine.agents.some(a => a.trustEvents.length > 0), 'Retrospective trust must run');
assert.notEqual(sender.epistemicRigor, originalRigor, 'Plasticity must run');
assert.ok(engine.agents.some(a => a.cognitiveLog.some(l => l.kind === 'gate')), 'Bounded confidence must gate');
assert.ok(engine.memes.size > 200, 'Mutations must be produced');
const frozen = captureEndState(engine, engine.roots[0].id);
assert.equal(frozen.vector.length, 256);
assert.ok(frozen.generation >= 0);
assert.equal(frozen.nearestTweets.length, 5);
const frozenTick = frozen.tick;
const metrics = engine.metrics();
assert.ok(metrics.generatedMutations > 0);
assert.equal(metrics.totalMemesCreated, 200 + metrics.generatedMutations);
assert.equal(metrics.mutatedShare, metrics.generatedMutations / metrics.totalMemesCreated);
assert.equal(engine.memes.size + engine.archivedMemes.size, metrics.totalMemesCreated);
assert.ok(engine.archivedMemes.size > 0, 'Extinct variants must be archived');
const archived = [...engine.archivedMemes.values()][0];
assert.equal(engine.getMeme(archived.id), archived);
assert.ok(engine.lineage(archived.id).some(entry => entry.meme.id === archived.id));
assert.ok(engine.lineage(archived.id).some(entry => entry.meme.id === archived.rootId));
assert.ok(engine.rankedMemes(Infinity, 'extinct', archived.id).some(row => row.meme.id === archived.id));
assert.ok(engine.rankedMemes(Infinity, 'circulating').every(row => row.held > 0));
assert.ok(engine.rankedMemes(30, 'mutations').every(row => row.meme.generation > 0));
assert.ok(engine.rankedMemes(Infinity, 'roots').every(row => row.meme.generation === 0));
const live = [...engine.memes.values()].filter(m => (engine.holders.get(m.id)?.size ?? 0) > 0);
assert.equal(metrics.liveMutations, live.filter(m => m.generation > 0).length);
assert.equal(metrics.liveMutatedShare, metrics.liveMutations / live.length);
assert.ok(Object.values(metrics).every(Number.isFinite));
engine.reset();
assert.equal(engine.metrics().generatedMutations, 0);
assert.equal(engine.metrics().mutatedShare, 0);
assert.equal(engine.metrics().maxGeneration, 0);
assert.equal(engine.archivedMemes.size, 0);
run(); assert.deepEqual(engine.metrics(), metrics, 'Resets must be deterministic');
const pca = new PcaProjector(); pca.fit(vectors);
assert.ok(Math.abs(dot(pca.pc1, pca.pc2)) < 1e-8);
assert.ok(pca.explained.every(v => v >= 0 && v <= 1));
// Startup and retry tests mock fetch only; production assets are untouched.
const originalFetch = globalThis.fetch;
let fail = true;
globalThis.fetch = async (url: string | URL | Request) => {
  const name = String(url);
  if (name.endsWith('trait_anchors.json')) return fail ? new Response('missing', { status: 404 }) : Response.json(anchorsJson);
  if (name.endsWith('.npy')) return new Response(buffer);
  return Response.json(data.tweets);
};
await useSimStore.getState().initialize();
assert.equal(useSimStore.getState().status, 'error');
assert.equal(useSimStore.getState().running, false);
fail = false;
await useSimStore.getState().initialize();
assert.equal(useSimStore.getState().status, 'ready');
assert.equal(useSimStore.getState().running, true);
assert.equal(useSimStore.getState().engine.tick, 1);
assert.equal((await loadDataset()).vectors.length, 200);
useSimStore.getState().engine.step();
useSimStore.getState().pause();
assert.equal(useSimStore.getState().metrics.tick, useSimStore.getState().engine.tick);
const beforeStep = useSimStore.getState().metrics.tick;
useSimStore.getState().play();
useSimStore.getState().stepOnce();
assert.equal(useSimStore.getState().running, false);
assert.equal(useSimStore.getState().metrics.tick, beforeStep + 1);
useSimStore.getState().runForTicks(3);
const target = useSimStore.getState().stopAtTick!;
for (let i = 0; i < 3; i++) useSimStore.getState().advanceTick();
assert.equal(useSimStore.getState().engine.tick, target);
assert.equal(useSimStore.getState().running, false);
assert.equal(useSimStore.getState().stopAtTick, null);
assert.equal(frozen.tick, frozenTick);
globalThis.fetch = originalFetch;
console.log(`Passed: real float16 ingestion, validation, selection, PCA, 240-tick mechanics, deterministic reset, loading failure/retry/autostart (${Math.round(performance.now() - start)}ms).`);
